services:
  python-dev:
    build: .
    volumes:
      - .:/app
    stdin_open: true  # Dockerの-iオプション（コンテナは実行中に外部からの入力を受け付けることができるようになります
    tty: true         # Dockerの-tオプション（対話的なシェルセッションなどを実行できるようになります
    deploy:
      resources:
        reservations:
          devices:    # GPUが使えるようになります
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "pip install -r requirements.txt && bash"

